name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest  # Menjalankan job di runner dengan Ubuntu terbaru
    container:
      image: python:3.9-slim  # Menjalankan job di dalam Docker container dengan image Python 3.9-slim
