name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    container:
      image: python:3.9-slim  # Menjalankan job di dalam Docker container dengan image Python 3.9
    
    services:
      postgres:
        image: postgres:alpine  # Menentukan image untuk Postgres
        ports:
          - 5432:5432  # Memetakan port 5432 di container ke port 5432 di host
        env:
          POSTGRES_PASSWORD: pgs3cr3t  # Menentukan password untuk Postgres
          POSTGRES_DB: testdb  # Menentukan nama database default
        options: >
          --health-cmd="pg_isready"  # Perintah untuk memeriksa kesehatan PostgreSQL
          --health-interval=10s  # Memeriksa kesehatan setiap 10 detik
          --health-timeout=5s  # Memiliki waktu tunggu 5 detik untuk pemeriksaan kesehatan
          --health-retries=5  # Menentukan jumlah upaya untuk memeriksa kesehatan

    steps:
      # Langkah untuk checkout kode
      - name: Checkout code
        uses: actions/checkout@v2

      # Langkah untuk menginstal dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      # Langkah untuk menjalankan linting dengan flake8
      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      # Langkah untuk menjalankan unit test dengan nose
      - name: Run unit tests with nose
        run: nosetests
        env:
          DATABASE_URI: "postgresql://postgres:pgs3cr3t@postgres:5432/testdb"
