jobs:
  build:
    services:
    # Layanan lainnya bisa didefinisikan di sini
    steps:
      - name: Checkout
        uses: actions/checkout@v2  # Menggunakan action untuk checkout kode
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel  # Upgrade pip dan wheel
          pip install -r requirements.txt  # Menginstall dependencies dari requirements.txt
